apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo0-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /datafiles/database/mongodb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo1-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /datafiles/database/mongodb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo2-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /datafiles/database/mongodb
